baseURL = 'https://blog.nicolas-dorier.com/'
languageCode = 'en-us'
title = "Nicolas Dorier's Blog"
theme = 'tailwind'

[outputFormats.RSS]
    mediaType              = "application/rss+xml"
    baseName               = "posts/feeds/feed.rss"
    rel                    = "alternate"
    isPlainText            = false
    isHTML                 = false
    noUgly                 = true

[params]
  author = 'Nicolas Dorier'
  keywords = "bitcoin, development"
  subtitle = ""
[params.meta]
  favicon = true
  description = 'A blog by Nicolas Dorier talking about Bitcoin and development'

[params.footer]
  poweredby = false
[params.header]
  logo = "images/NicolasDorier.png"
  sticky = false

[[params.social_media.items]]
  enabled = true
  title = '@NicolasDorier on GitHub'
  icon = 'brand-github'
  link = 'https://github.com/NicolasDorier/'

[[params.social_media.items]]
  enabled = true
  title = '@NicolasDorier on X'
  icon = 'brand-x'
  link = 'https://x.com/NicolasDorier'
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$','$']]
